# TP: Construire un tableau de bord

In [1]:
import pandas as pd
import plotly.graph_objects as go 
import calendar

# Préparation des données

## Importation des données

In [2]:
# importation de la table de données
data = pd.read_csv("datasets/data.csv")
display(data.head())
# chaque ligne correspond à une vente

,Unnamed: 0,CustomerID,Gender,Location,Tenure_Months,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,...,Avg_Price,Delivery_Charges,Coupon_Status,GST,Date,Offline_Spend,Online_Spend,Month,Coupon_Code,Discount_pct
0,0,17850.0,M,Chicago,12.0,16679.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,153.71,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
1,1,17850.0,M,Chicago,12.0,16680.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,153.71,6.5,Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
2,2,17850.0,M,Chicago,12.0,16696.0,2019-01-01,GGOENEBQ078999,Nest Cam Outdoor Security Camera - USA,Nest-USA,...,122.77,6.5,Not Used,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
3,3,17850.0,M,Chicago,12.0,16699.0,2019-01-01,GGOENEBQ079099,Nest Protect Smoke + CO White Battery Alarm-USA,Nest-USA,...,81.50,6.5,Clicked,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0
4,4,17850.0,M,Chicago,12.0,16700.0,2019-01-01,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,...,153.71,6.5,Clicked,0.1,1/1/2019,4500.0,2424.5,1,ELEC10,10.0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52955 entries, 0 to 52954
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           52955 non-null  int64
 1   CustomerID           52924 non-null  float64
 2   Gender               52924 non-null  object
 3   Location             52924 non-null  object
 4   Tenure_Months        52924 non-null  float64
 5   Transaction_ID       52924 non-null  float64
 6   Transaction_Date     52924 non-null  object
 7   Product_SKU          52924 non-null  object
 8   Product_Description  52924 non-null  object
 9   Product_Category     52955 non-null  object
 10  Quantity             52924 non-null  float64
 11  Avg_Price            52924 non-null  float64
 12  Delivery_Charges     52924 non-null  float64
 13  Coupon_Status        52924 non-null  object
 14  GST                  52924 non-null  float64
 15  Date                 52924 non-null  object
 16  Offline_Spend        52924 non-null  float64
 17  Online_Spend         52924 non-null  float64
 18  Month                52955 non-null  int64
 19  Coupon_Code          52555 non-null  object
 20  Discount_pct         52555 non-null  float64
dtypes: float64(10), int64(2), object(9)
memory usage: 8.5+ MB

### Suppression des colonnes useless

- Supprimer une colonne: data.drop(columns=["aaa","bbb"])

In [4]:
data = data.drop(columns=['Unnamed: 0', 'Tenure_Months','Transaction_ID', 'Product_SKU', 'Product_Description','Delivery_Charges','Coupon_Status','GST', 'Date', 'Offline_Spend', 'Online_Spend', 'Coupon_Code'])

In [5]:
display(data.head(5))

,CustomerID,Gender,Location,Transaction_Date,Product_Category,Quantity,Avg_Price,Month,Discount_pct
0,17850.0,M,Chicago,2019-01-01,Nest-USA,1.0,153.71,1,10.0
1,17850.0,M,Chicago,2019-01-01,Nest-USA,1.0,153.71,1,10.0
2,17850.0,M,Chicago,2019-01-01,Nest-USA,2.0,122.77,1,10.0
3,17850.0,M,Chicago,2019-01-01,Nest-USA,1.0,81.50,1,10.0
4,17850.0,M,Chicago,2019-01-01,Nest-USA,1.0,153.71,1,10.0

### Remplacer les NaN par des 0 dans la colonne `CustomerID`

In [6]:
# Compte le nombre de NA dans chaque colonne
data.isna().sum()

CustomerID           31
Gender               31
Location             31
Transaction_Date     31
Product_Category      0
Quantity             31
Avg_Price            31
Month                 0
Discount_pct        400
dtype: int64

In [7]:
# On remplace les NA dans la colonne ID client par 0. 
data["CustomerID"] = data["CustomerID"].fillna(0)

In [8]:
#Vérification 
data.isna().sum()

CustomerID            0
Gender               31
Location             31
Transaction_Date     31
Product_Category      0
Quantity             31
Avg_Price            31
Month                 0
Discount_pct        400
dtype: int64

### Suppression des clientsID égale à 0

In [9]:
data = data[data['CustomerID'] != 0]

### Convertir la colonne `CustomerID` en int

In [10]:
# Convertir la colonnes 'CustomerID' en entier
data["CustomerID"] = data["CustomerID"].astype("int32")
data.info()
data.isna().sum()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52924 entries, 0 to 52923
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        52924 non-null  int32
 1   Gender            52924 non-null  object
 2   Location          52924 non-null  object
 3   Transaction_Date  52924 non-null  object
 4   Product_Category  52924 non-null  object
 5   Quantity          52924 non-null  float64
 6   Avg_Price         52924 non-null  float64
 7   Month             52924 non-null  int64
 8   Discount_pct      52524 non-null  float64
dtypes: float64(3), int32(1), int64(1), object(4)
memory usage: 3.8+ MB

CustomerID            0
Gender                0
Location              0
Transaction_Date      0
Product_Category      0
Quantity              0
Avg_Price             0
Month                 0
Discount_pct        400
dtype: int64

### Convertir `Transaction_date` au format date

In [11]:
#Convertir les "Transaction_date" en date 

data["Transaction_Date"] = pd.to_datetime(data["Transaction_Date"], errors='coerce')
# coerce transforme les NaN en NaT
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 52924 entries, 0 to 52923
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        52924 non-null  int32
 1   Gender            52924 non-null  object
 2   Location          52924 non-null  object
 3   Transaction_Date  52924 non-null  datetime64[ns]
 4   Product_Category  52924 non-null  object
 5   Quantity          52924 non-null  float64
 6   Avg_Price         52924 non-null  float64
 7   Month             52924 non-null  int64
 8   Discount_pct      52524 non-null  float64
dtypes: datetime64[ns](1), float64(3), int32(1), int64(1), object(3)
memory usage: 3.8+ MB

In [12]:
display(data.tail())

,CustomerID,Gender,Location,Transaction_Date,Product_Category,Quantity,Avg_Price,Month,Discount_pct
52919,13155,F,California,2019-03-10,Gift Cards,1.0,250.00,3,30.0
52920,18077,M,Chicago,2019-03-28,Gift Cards,1.0,25.00,3,30.0
52921,16085,M,California,2019-10-06,Notebooks & Journals,1.0,10.80,10,10.0
52922,16085,M,California,2019-10-06,Notebooks & Journals,1.0,9.60,10,10.0
52923,13659,F,Chicago,2019-10-06,Notebooks & Journals,1.0,5.59,10,10.0

### Création d'une colonne Total_price

In [13]:
#Créer une colonne Total_price 
data["Total_price"] = data["Quantity"] * (data["Avg_Price"] *(1 - (data["Discount_pct"]*0.01)))
display(data.head())
display(data.tail())

,CustomerID,Gender,Location,Transaction_Date,Product_Category,Quantity,Avg_Price,Month,Discount_pct,Total_price
0,17850,M,Chicago,2019-01-01,Nest-USA,1.0,153.71,1,10.0,138.339
1,17850,M,Chicago,2019-01-01,Nest-USA,1.0,153.71,1,10.0,138.339
2,17850,M,Chicago,2019-01-01,Nest-USA,2.0,122.77,1,10.0,220.986
3,17850,M,Chicago,2019-01-01,Nest-USA,1.0,81.50,1,10.0,73.350
4,17850,M,Chicago,2019-01-01,Nest-USA,1.0,153.71,1,10.0,138.339

,CustomerID,Gender,Location,Transaction_Date,Product_Category,Quantity,Avg_Price,Month,Discount_pct,Total_price
52919,13155,F,California,2019-03-10,Gift Cards,1.0,250.00,3,30.0,175.000
52920,18077,M,Chicago,2019-03-28,Gift Cards,1.0,25.00,3,30.0,17.500
52921,16085,M,California,2019-10-06,Notebooks & Journals,1.0,10.80,10,10.0,9.720
52922,16085,M,California,2019-10-06,Notebooks & Journals,1.0,9.60,10,10.0,8.640
52923,13659,F,Chicago,2019-10-06,Notebooks & Journals,1.0,5.59,10,10.0,5.031

# Fonction

### fonction chiffre d'affaire

In [14]:
## fonction chiffre d'affaire

def CA(data):
    """
    La fonction permet de calculer le chiffre d'affaire, c'est à dire prix fois quantité.
    Renvoie le chiffre d'affaire
    """
    return data["Total_price"].sum()
    

print(CA(data))

3717667.247

### Fonction top 10 meilleure vente (freq)

In [15]:
def top10(data):
    """
    La fonction prend en entrée la table de données et vient calculer le CA total 
    après remise et retourne le résultat
    """
    top_10 = data.groupby(["Product_Category","Gender"])[["Total_price"]]

    return top_10.agg('sum').reset_index().sort_values(["Total_price"], ascending = False).head(20)

In [16]:
top10(data)

        Product_Category Gender  Total_price
32              Nest-USA      F  1265562.510
33              Nest-USA      M   781415.198
4                Apparel      F   305768.453
28                  Nest      F   240721.773
5                Apparel      M   167609.510
29                  Nest      M   162986.973
36                Office      F   141269.152
12             Drinkware      F   100127.447
8                   Bags      F    83350.621
37                Office      M    81960.104
13             Drinkware      M    61007.784
34  Notebooks & Journals      F    49488.215
35  Notebooks & Journals      M    39615.575
9                   Bags      M    38012.102
24             Lifestyle      F    36704.803
30           Nest-Canada      F    34211.424
20              Headgear      F    28138.448
25             Lifestyle      M    23738.249
31           Nest-Canada      M    22736.578
21              Headgear      M    15662.174

## Fonction indicateur_du-mois 
`indicateur_du_mois(data, current_month=12, freq=True, abbr=False)`

In [17]:
def indicateur_mois(data, current_month):
    """
    Pour un mois donné, calcule :
    - Le CA du mois en cours (n)
    - Le CA du même mois en n-1
    - La variation du CA entre n et n-1
    - Le nombre de ventes en n et en n-1
    
    Paramètres :
    - data : DataFrame contenant les transactions
    - current_month : mois cible au format datetime (ex: pd.Timestamp("2023-06-01"))
    """
    
    # Définir le mois n-1
    previous_month = current_month - pd.DateOffset(months=1)
    
    # Filtrer les données pour n et n-1
    data_n = data[data['Transaction_Date'].dt.to_period('M') == current_month.to_period('M')]
    data_n1 = data[data['Transaction_Date'].dt.to_period('M') == previous_month.to_period('M')]
    
    # Calcul du CA via ta fonction CA()
    ca_n = CA(data_n)
    ca_n1 = CA(data_n1)
    

    
    # Calcul du nombre de ventes
    nb_ventes_n = len(data_n)
    nb_ventes_n1 = len(data_n1)
    
    # Résultat sous forme de dictionnaire
    resultat = {
    "mois"          : current_month.strftime("%B"),
    "ca_n"          : round(ca_n, 2),
    "ca_n1"         : round(ca_n1, 2),
    "nb_ventes_n"   : nb_ventes_n,
    "nb_ventes_n1"  : nb_ventes_n1,
}
    return resultat

In [18]:
current_month = pd.Timestamp("2019-12-01")
indicateur_mois(data, current_month)

{'mois': 'December',
 'ca_n': 366280.73,
 'ca_n1': 406866.13,
 'nb_ventes_n': 4502,
 'nb_ventes_n1': 3961}

# Construction table de 100 dernières ventes

L'objectif est de filtrer les commandes par date pour ne prendre que les 100 dernière.

In [19]:

data100 = data.sort_values("Transaction_Date", ascending  = False).head(100)
data100.head(3)

,CustomerID,Gender,Location,Transaction_Date,Product_Category,Quantity,Avg_Price,Month,Discount_pct,Total_price
5097,14410,F,New York,2019-12-31,Nest-USA,1.0,121.30,12,30.0,84.910
5075,14606,F,Chicago,2019-12-31,Nest-USA,2.0,121.30,12,30.0,169.820
7025,14410,F,New York,2019-12-31,Apparel,1.0,48.92,12,30.0,34.244

# Graphiques

## Graphique top 10 selon le sexe

In [20]:
import plotly.express as px
import pandas as pd

df = top10(data)
fig_top10 = px.bar(
    df,
    x='Total_price',
    y='Product_Category',
    color='Gender',              
    barmode='group',             
    category_orders={
        'Product_Category': df.groupby('Product_Category')['Total_price']
                               .sum()
                               .sort_values(ascending=False)  # ascending=True car l'axe Y est inversé dans plotly
                               .index.tolist()
    },
    title = "Top 10 des produits qui rapporte le plus par genre", 
    labels = {'Total_price':"Chiffre d'affaires", 'Product_Category': 'Catégorie de produit'}
)

fig_top10.show()

## Graphique évolution du CA par semaine

In [21]:
import plotly.express as px

data["semaine"] = data["Transaction_Date"].dt.to_period("W") # On ajoute une colonne "semaine" au data frame en prenant les semaines
ca_hebdo = data.groupby("semaine")["Total_price"].sum().reset_index()
ca_hebdo["semaine"] = ca_hebdo["semaine"].dt.to_timestamp()
ca_hebdo

graph_evolCA = px.line(ca_hebdo, x = "semaine", y = "Total_price", title= "Evolution du chiffre d'affaires par semaine",
              labels= {"semaine": "Semaine", "Total_price": "Chiffre d'affaires (€)"})
graph_evolCA.show()

## Indicateurs de performance

### Indicateur du nombre de ventes

In [22]:
import plotly.graph_objects as go

indicateur_vente= go.Figure()
indicateur_vente.add_trace(
    go.Indicator(value = indicateur_mois(data, current_month)["nb_ventes_n"], 
        mode = "number+delta"
    )
)

indicateur_vente.update_layout( 
    
    template = {'data' : {'indicator': [{ 
    	'title': {'text': indicateur_mois(data, current_month)["mois"]}, 
        'mode' : "number+delta+gauge",
        'delta' : {'reference': indicateur_mois(data, current_month)["nb_ventes_n1"]}}]
        }
     }
)

indicateur_vente.show()

### Indicateur chiffre d'affaire du mois

In [23]:
import plotly.graph_objects as go

indicateur_CA = go.Figure()
indicateur_CA.add_trace(
    go.Indicator(value = indicateur_mois(data, current_month)["ca_n"], 
        mode = "number+delta", 
        domain = {'row': 1, 'column': 1}
    )
)

indicateur_CA.update_layout( 
    grid = {
        'rows': 1, 'columns': 1, 
        'pattern': "independent"
    },
    template = {'data' : {'indicator': [{ 
    	'title': {'text': indicateur_mois(data, current_month)["mois"]}, 
        'mode' : "number+delta+gauge",
        'delta' : {'reference': indicateur_mois(data, current_month)["ca_n1"]}}]
        }
     }
)

indicateur_CA.show()

# Maquette application

### brouillon

In [24]:
import dash 
from dash import html, dcc 
import dash_bootstrap_components as dbc 
import plotly.express as px
import pandas as pd
from dash import dash_table

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container([
    dbc.Row([
        dbc.Col(children='ECAP store',width=6, style={'border':'solid'}),# Première ligne avec une colonne
        dbc.Col(children= 
                dcc.Dropdown(
    options=[{"label": loc, "value": loc} for loc in data["Location"].unique()],
    value=None,  # aucune valeur sélectionnée par défaut
    multi=True,
    searchable=True,
    placeholder="Sélectionner une ville",
    disabled=False,
),width=6, style={'border':'solid'})
    ],style={'height':'100px'}), # première ligne avec une colonne contenant un dropdown

#------------------------- Colonne de gauche ---------------------------------# 
    dbc.Row([
        dbc.Col([
            dbc.Row([

                dbc.Col(children= dcc.Graph(figure=fig_top10,style= {'heigth':'100%','width': '100%'})
                        ,style={'width':'150px','border':'solid'}),

                dbc.Col(children= 'b',style={'width':'150px','border':'solid'})
            ],style={'height':'180px'}),# style de la colonne 
            dbc.Row(children= 'c',
                    style={'border':'solid','height':'380px'})
        ],width=5), # Deuxième ligne avec une colonne contenant deux lignes dont une contient deux colonnes
        
        #------------------------------colonne de droite -----------------------------------#
        dbc.Col([
    dbc.Row(
        children='d',
        style={'border': 'solid', 'height': '280px'}
    ),

    dbc.Row(
        children='e',
        style={'border': 'solid', 'height': '280px'}
    )
], width=7)   # ta colonne 60% (la largeur de la page = 12)
 # deuxième ligne avec une colonne contenant deux lignes
    ]),
    
], fluid=True)

#-------------- lancer l'app -----------------------# 
if __name__ == "__main__":
    app.run_server(debug=True, port = 8040, jupyter_mode = "external")

Dash app running on http://127.0.0.1:8040/

### App

In [30]:
import dash
from dash import html, dcc 
import dash_bootstrap_components as dbc 
import plotly.express as px
import pandas as pd
from dash import dash_table

app = dash.Dash(external_stylesheets=[dbc.themes.BOOTSTRAP])

app.layout = dbc.Container(
    fluid=True,
    children=[
        dbc.Row([
                dbc.Col(children= html.H2("ECAP Store"),
                        style={"margin": "0", "lineHeight": "50px"},
                        width=6),# Première ligne avec une colonne
                dbc.Col(children= 
                    dcc.Dropdown(
                                options=[{"label": loc, "value": loc} for loc in data["Location"].unique()],
                                value=None,  # aucune valeur sélectionnée par défaut
                                multi=True,
                                searchable=True,
                                placeholder="Sélectionner une ville",
                                disabled=False,
                                style= {'margin':'6px',"marginRight": "10px"}
                ),
                    width=6)
                    ],style={'height':'50px', 'background-color':'skyblue'}
                ),
    
        dbc.Row(
            style={"height": "100vh", "margin": "0"},
            children=[

                # ── COLONNE GAUCHE (5/12) ──────────────────────────────────
                dbc.Col(
                    width=5,
                    style={"padding": "0"},
                    children=[

                        # Ligne 1 gauche : a (indicateur CA) + b (indicateur vente)
                        dbc.Row(
                            style={
                                "height": "30%",
                                "margin":"O"
                            },
                            children=[
                                #  indicateur CA
                                dbc.Col(
                                    width=6,
                                    style={
                                        "padding": "5px",
                                        "height": "100%",
                                    },
                                    children=dcc.Graph(
                                        figure=indicateur_CA,
                                        style={"width": "100%", "height": "100%"},
                                    ),
                                ),
                                # indicateur vente
                                dbc.Col(
                                    width=6,
                                    style={
                                        "padding": "0",
                                        "height": "100%"
                                        },
                                    children=dcc.Graph(
                                        figure=indicateur_vente,
                                        style={"width": "100%","height": "100%"},
                                    ),
                                ),
                            ],
                        ),

                        #fig_top10
                        dbc.Row(
                            style={"height": "65%", "margin": "0"},
                            children=[
                                dbc.Col(
                                    width=12,
                                    style={"padding": "0", "height": "100%"},
                                    children=dcc.Graph(
                                        figure=fig_top10,
                                        style={"width": "100%", "height": "100%"},
                                    ),
                                )
                            ],
                        ),
                    ],
                ),

                # ── COLONNE DROITE (7/12) ──────────────────────────────────
                dbc.Col(
                    width=7,
                    style={"padding": "0"},
                    children=[

                        # Graphe evolution du CA
                        dbc.Row(
                            style={
                                "height": "50%",
                                "margin": "0",
                                
                            },
                            children=[
                                dbc.Col(
                                    width=12,
                                    style={"padding": "8px", "height": "100%"},
                                    children=
                                    dcc.Graph( figure=graph_evolCA,
                                        style={"width": "100%", "height": "100%"}) ,
                                )
                            ],
                        ),

                        # DataTable
                        dbc.Row(
                            style={"height": "50%", "margin": "0"},
                            children=[
                                dbc.Col(
                                    width=12,
                                    style={"padding": "8px", "height": "100%"},
                                    children=html.Div(
                                        children=[
                                            html.H4("Table des 100 dernières ventes"),
                                            dash_table.DataTable(
                                                data=data100.to_dict("records"),
                                                columns=[
                                                    {"name": col, "id": col}
                                                    for col in data100.columns
                                                ],
                                                page_size=10,
                                                style_table={
                                                    "width": "100%",
                                                    "overflowX": "auto",
                                                    "height": "250px",
                                                },
                                                filter_action="native",
                                                sort_action="native",
                                                style_cell={"textAlign": "left"},
                                            ),
                                        ],
                                        style={"width": "100%", "display": "block"},
                                    ),
                                )
                            ],
                        ),
                    ],
                ),
            ],
        )
    ],
)

if __name__ == "__main__":
    app.run_server(debug=True, port = 8060, jupyter_mode = "external")

Dash app running on http://127.0.0.1:8060/